CREATE TABLE "DB" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT UNIQUE NOT NULL,
    "masterPassword" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "uri" TEXT UNIQUE NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);